### ISSUE TITLE
Documentation for Log4j Plugin Cache Transformer

### ISSUE THREAD

**Issue by AdamDanischewski** [apache/logging-log4j-transform#54]
I tried using the example for Log4j Plugin Cache Transformer example as listed in the adoc and also using examples found on the transformers official documentation.  Neither made mention of a need to supply id/phase to the execution section, without it I received errors. 

```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.apache.logging.log4j</groupId>
						<artifactId>log4j-transform-maven-shade-plugin-extensions</artifactId>
						<version>0.1.0</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>shade-jar-with-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
								<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
								<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<manifestEntries>
										<Multi-Release>true</Multi-Release>
									</manifestEntries>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>

```
Note: 
< id >shade-jar-with-dependencies< /id >
	 < phase >package< /phase >

in the execution section. 

Without it I get an error message on **mvn package**, like: 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.4.1:shade (default) on project demo: Unable to parse configuration of mojo org.apache.maven.plugins:maven-shade-plugin:3.4.1:shade for parameter resource: Cannot find 'resource' in class org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer -> [Help 1]`

**Comment by vy** [comment]
@AdamDanischewski, thanks so much, fixed the docs. Note that we now have a website: https://logging.apache.org/log4j/transform :rocket:
